name: "Init Terraform"
description: "Initialize Terraform configuration and set up workspace"
inputs:
  s3-bucket-name:
    description: "Terraform remote state S3 bucket name"
    required: true
  dynamodb-table-name:
    description: "Terraform remote state DynamoDB table name"
    required: true
  account-id:
    description: "AWS account ID to deploy to"
    required: true
  tfvars-file:
    description: "Path to the tfvars file (relative to the terraform directory)"
    required: true
  domain-name:
    description: "Domain name of the application"
    required: true
outputs:
  workspace:
    description: "Terraform workspace name"
    value: ${{ steps.init.outputs.workspace }}
  tfvars-file:
    description: "Path to the tfvars file (relative to the terraform directory)"
    value: ${{ steps.init.outputs.tfvars-file }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run terraform init script
      id: init
      run: init.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
      env:
        S3_BUCKET_NAME: ${{ inputs.s3-bucket-name }}
        DYNAMODB_TABLE_NAME: ${{ inputs.dynamodb-table-name }}
        ACCOUNT_ID: ${{ inputs.account-id }}
        DOMAIN_NAME: ${{ inputs.domain-name }}
        TFVARS_FILE: ${{ inputs.tfvars-file }}
