name: "Deploy Terraform"
description: "Deploy Terraform code to AWS account"
inputs:
  workspace:
    description: "Terraform workspace name"
    required: true
  tfvars-file:
    description: "Path to the tfvars file (relative to the terraform directory)"
    required: true
  account-id:
    description: "AWS account ID to deploy to"
    required: true
  domain-name:
    description: "Domain name of the application"
    required: true
outputs:
  app-url:
    description: "URL of the deployed application"
    value: ${{ steps.deploy.outputs.app-url }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run terraform deploy script
      id: deploy
      run: deploy.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
      env:
        WORKSPACE: ${{ inputs.workspace }}
        TFVARS_FILE: ${{ inputs.tfvars-file }}
        ACCOUNT_ID: ${{ inputs.account-id }}
        DOMAIN_NAME: ${{ inputs.domain-name }}
