version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "@types/*"
      type-dependencies:
        patterns:
          - "@types/*"
    open-pull-requests-limit: 10
    ignore:
      update-types: "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      update-types: "version-update:semver-major"
