name: "Deploy Code"
description: "Deploy code (build artifact) to S3 bucket and invalidate CloudFront distribution"
inputs:
  tfvars-file:
    description: "Path to the tfvars file (relative to the terraform directory)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run code deploy script
      id: deploy
      run: deploy.sh
      shell: bash
      env:
        TFVARS_FILE: ${{ inputs.tfvars-file }}
