name: "Destroy Terraform"
description: "Destroy Terraform resources in AWS account"
inputs:
  s3-bucket-name:
    description: "Terraform remote state S3 bucket name"
    required: true
  dynamodb-table-name:
    description: "Terraform remote state DynamoDB table name"
    required: true
  aws-region:
    description: "AWS region where the application is"
    required: true
    default: "ap-southeast-1"
  account-id:
    description: "AWS account ID where the application is"
    required: true
  domain-name:
    description: "Domain name of the application"
    required: true
  environment:
    description: "Environment of the application"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Assume AWS role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ inputs.aws-region }}
    - name: Set GitHub Path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Run destroy script
      id: destroy
      run: destroy.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
      env:
        S3_BUCKET_NAME: ${{ inputs.s3-bucket-name }}
        DYNAMODB_TABLE_NAME: ${{ inputs.dynamodb-table-name }}
        ACCOUNT_ID: ${{ inputs.account-id }}
        AWS_REGION: ${{ inputs.aws-region }}
        DOMAIN_NAME: ${{ inputs.domain-name }}
        ENVIRONMENT: ${{ inputs.environment }}
