name: "Publish blog"
description: "Put a new blog to the S3 bucket and create CloudFront cache invalidation"
inputs:
  api-key:
    description: "API key for API Gateway REST API"
    required: true
outputs:
  blog-url:
    description: "URL link of the published blog"
    value: ${{ steps.deploy.outputs.blog-url }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run publish script
      id: publish
      run: publish.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
      env:
        API_KEY: ${{ inputs.api-key }}
