name: "Validate tag"
description: "Verify whether tags assigned to the blog do exist or not"
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run deploy script
      id: deploy
      run: validate.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
