name: "Validate tag"
description: "Verify whether tags assigned to the blog do exist or not"
inputs:
  s3-bucket-name:
    description: "Terraform remote state S3 bucket name"
    required: true
  dynamodb-table-name:
    description: "Terraform remote state DynamoDB table name"
    required: true
  account-id:
    description: "AWS account ID where the application is"
    required: true
  tfvars-file:
    description: "Path to the tfvars file (relative to the terraform directory)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Run deploy script
      id: deploy
      run: validate.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
      env:
        S3_BUCKET_NAME: ${{ inputs.s3-bucket-name }}
        DYNAMODB_TABLE_NAME: ${{ inputs.dynamodb-table-name }}
        ACCOUNT_ID: ${{ inputs.account-id }}
        TFVARS_FILE: ${{ inputs.tfvars-file }}
