name: Publish new blog post

on:
  pull_request:
    branches: [blog/**]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm test

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
