name: Deploy Feature
run-name: Deploy new feature '${{ github.head_ref }}' (${{ github.sha }}) to production environment

on:
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-to-prod:
    if: |
      startsWith(github.head_ref, 'blog/') == false &&
      github.event.pull_request.merged == true &&
      contains(github.head_ref, '/skip-ci') == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Get target run ID
        id: get-run-id
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "test-feature.yml",
              branch: "${{ github.head_ref }}",
              event: "pull_request",
              status: "success",
              per_page: 1
            });
            return runs.data.workflow_runs[0].id;
          result-encoding: string
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.workspace }}/terraform/assets/dist
          run-id: ${{ steps.get-run-id.outputs.result }}
      - name: Deploy Terraform
        uses: ./.github/actions/deploy-terraform
        with:
          s3-bucket-name: ${{ vars.TF_REMOTE_STATE_S3_BUCKET }}
          dynamodb-table-name: ${{ vars.TF_REMOTE_STATE_DYNAMODB_TABLE }}
          account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          domain-name: ${{ vars.DOMAIN_NAME }}
          is-production: true
          environment: ${{ vars.STAGE }}
