name: Terminate Staging
run-name: Terminate staging environment created from '${{ github.head_ref }}' (${{ github.sha }})

on:
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terminate-staging:
    if: |
      startsWith(github.head_ref, 'blog/') == false &&
      startsWith(github.head_ref, 'dependabot/') == false &&
      contains(github.head_ref, '/skip-ci') == false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Destroy Staging Terraform
        uses: ./.github/actions/destroy-terraform
        with:
          s3-bucket-name: ${{ vars.TF_REMOTE_STATE_S3_BUCKET }}
          dynamodb-table-name: ${{ vars.TF_REMOTE_STATE_DYNAMODB_TABLE }}
          account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          domain-name: ${{ vars.DOMAIN_NAME }}
          tfvars-file: tfvars/staging.tfvars
